<?php

namespace Vanguard\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\This;
use Vanguard\User;

class Appointment extends Model
{
    use HasFactory;

    protected $fillable = [
        'time',
        'date',
        'user_id',
        'status',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getDateTimeAttribute()
    {
        return $this->date . " " . $this->time;
    }

    public function getDateCreateAttribute()
    {
        return date('d-m-Y', strtotime($this->created_at));
    }

    public function getStatussAttribute()
    {
        switch ($this->status) {
            case 'Waiting':
                return '<label for="" class="badge badge-warning">Đang chờ</label>';
            case 'Confirm':
                return '<label for="" class="badge badge-info">Xác nhận</label>';
            case 'Cancelled':
                return '<label for="" class="badge badge-primary">Bị huỷ</label>';
            case 'Success':
                return '<label for="" class="badge badge-success">Thành công</label>';
        }
    }

    public function getStAttribute()
    {
        switch ($this->status) {
            case 'Waiting':
                return '<label for="" class="badge bg-warning">Đang chờ</label>';
            case 'Confirm':
                return '<label for="" class="badge bg-info">Xác nhận</label>';
            case 'Cancelled':
                return '<label for="" class="badge bg-primary">Bị huỷ</label>';
            case 'Success':
                return '<label for="" class="badge bg-success">Thành công</label>';
        }
    }

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::created(function ($appointment) {
//
//        });
//    }
}
